### ISSUE TITLE
exp가 NaN으로 표시됌

### ISSUE THREAD

**Issue by ByeongsuPark** [hyp3rflow/github-readme-solvedac#3]
안녕하세요.
좋은 프로젝트 감사합니다. 항상 잘 쓰고 있습니다.

![캡처](https://user-images.githubusercontent.com/39683194/109968638-57392180-7d36-11eb-870d-ea2a217c75cb.JPG)

위 이미지처럼 카드에서 경험치가 NaN으로 표시되는 현상이 있어서 이슈 남깁니다.
최근 solved.ac 레이팅 시스템 변경으로 인해
API 업데이트가 있었던 것으로 알고 있습니다.
지금 코드가 업데이트 이전 API기준인거 같아서 혹시 따로 업데이트 할 계획은 없으신가요?

**Comment by hyp3rflow** [comment]
안녕하세요.
제 프로젝트에 관심을 가져주시고 사용해주셔서 정말 감사드립니다. :)

수정을 생각하고 있던 참인데 이슈를 통해 의견을 전달해주셔서 빠르게 작업할 수 있었습니다. (#4)
앞으로도 수정이나 원하시는 점이 있다면 편하게 말씀해주시면 감사하겠습니다.

다시 한번 감사드립니다. 😄
